---
title: "Frog Tadpole Tail-Clip Protocol"
author: "Ryan Peek"
date: "*Updated: `r format(Sys.Date())`*"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

To collect DNA for high quality genomic sequencing and analysis of populations and landscape genetics, it is now possible to use minimal amounts of tissue, which reduces handling time and is non-lethal for individuals. Research has shown tipping the distal end of a tadpole/larvae tail (i.e., clipping a few millimeters from the tip of the tail) ranked as one the best sampling methods for species welfare. Buccal swabbing (**Goldberg et al. 2003, Broquet et al. 2007**) and collecting whole tapoles was second for individual welfare, as defined as level of suffering experiences by an animal and level of suffering combined with loss of future life (see **Parris et al. 2010**, Assessing ethical trade-offs in ecological field studies).

Anesthetizing individuals may be possible but can be more harmful (increases chances of mortality), as well as being difficult in field situations where different developmental stages of tadpole may occur in the same location.
Use of gloves (nitrile/latex) has been shown to have sub-lethal and lethal impacts on tadpoles (**Cashins et al. 2008**), thus gloves will not be used when handling individuals but hands will be washed and sanitized between sampling events.

## Materials

 - **Coin Envelopes** Available at most office supply stores, 3.5" envelopes work well. Pre-label envelopes with a unique 4-5 digit number, use sequential numbering to avoid duplication.

 - **Acid Free Paper** use acid free paper cut into approximately 2" squares. The tail clip can be placed in the paper and folded around the tissue.

 - **Dessicant** Available widely, bead dessicant can be bought in bulk and used in bags with envelopes.

## Sampling

When observed, individual tadpoles (preferred) will be netted and placed in cups of water from stream location. One sample per individual will be taken, a small (<2 mm) tip of the tadpole tail will be removed using scissors, and tissue will be placed in a square of acid free paper.

If possible, allow sample to air dry for a few minutes before folding paper around the tissue sample so it will not slide out, but avoid creasing directly on the sample. Place the folded paper with tissue sample into a labeled paper coin envelope, in a plastic ziploc bag with dessicant. After clipping the tip of the tadpole tail, tadpoles will be observed in cup for 1-2 minutes, and then released at location of capture.

As stated in **Snell and Evans, 2006**, "The loss of tail tips in anuran larvae has been shown to cause little loss of ecological fitness and may in fact be a mechanism to reduce predation (**Wilbur & Semlitsch 1990**) somewhat analogous to tail loss in lizards."

All scissors/tweezers used in tail clipping will be sanitized with alcohol and wipes between individuals. Because of literature showing potential detrimental impacts of latex/nitrile gloves on tadpoles, gloves will not be when handling larvae. Hands will be washed in local water before and after each handling event. Furthermore, there should be no contact between the person doing the sampling and the actual DNA being collected. All scissors/tweezers will be sterilized between tadpole samples, thus potential for cross contamination is very low. After each capture, individuals wash and sterilize hands with alcohol wipes to further minimize any chance of cross-contamination.

## Literature

Broquet, T., L. Berset-Braendli, G. Emaresi, and L. Fumagalli. 2007. Buccal swabs allow efficient and reliable microsatellite genotyping in amphibians. Conservation Genetics 8:509–511.

Cashins, S. C., R. A. Alford, and L. F. Skerratt. 2008. Lethal Effect of Latex, Nitrile, and Vinyl Gloves on Tadpoles. Herpetological Review 39:298–301.

Goldberg, C. S., M. E. Kaplan, and C. R. Schwalbe. 2003. From the frog’s mouth: buccal swabs for collection of DNA from amphibians. Herpetological Review.

Parris, K. M., S. C. McCall, M. A. McCarthy, B. A. Minteer, K. Steele, S. Bekessy, and F. Medvecky. 2010. Assessing ethical trade-offs in ecological field studies. The Journal of Applied Ecology 47:227–234.

Snell, C., and I. H. Evans. 2006. Discrimination of moor frog (*Rana arvalis*) and common frog (*Rana temporaria*) individuals using a RAPD technique. The Herpetological journal 16:363–369.

Vences, M., M. Puente, S. Nieto, and D. R. Vieites. 2002. Phenotypic plasticity of anuran larvae: environmental variables influence body shape and oral morphology in *Rana temporaria* tadpoles. Journal of zoology 257:155–162.

Wilbur, H. M., and R. D. Semlitsch. 1990. Ecological Consequences of Tail Injury in Rana Tadpoles. Copeia 1990:18–24.
